---
title: '20191121'
author: "邱奕勳"
date: "2019/11/21"
output: html_document
---

```{r}
library(psych)
library(clipr)
library(dplyr)
```

```{r}
library(xml2)
#library(rvest)
```

```{r}
# 讀入html
"https://www.cakeresume.com/jean-pang" %>%
  read_html() -> nodes0
```

```{r}
nodes0 %>% xml_find_all(
  xpath='//*[@id="item"]/div[6]/div/div[2]/div[2]'
) -> nodes1
```

```{r}
nodes1 %>% xml_text()
```
#看小孩
```{r}
nodes1 %>% xml_children()
```
#選第一個小孩
```{r}
nodes1 %>% xml_child(1)
```
```{r}
nodes1 %>% xml_child(1) %>% xml_children() #確定沒有小孩
```

```{r}
nodes1 %>% xml_child(1) %>% xml_text() 
```

```{r}
nodes1 %>% xml_child(2) %>% xml_text()
```

## emajor_ website practice
```{r}
"https://bookdown.org/tpemartin/108-1-emajor/" %>% read_html() -> emajor_nodes0
```

```{r}
emajor_nodes0 %>% xml_find_all(xpath='//*[@id="課程說明"]') -> emajor_nodes1
```

```{r}
emajor_nodes1 %>% xml_children()
```
```{r}
emajor_nodes1 %>% xml_child(1) %>% xml_text()

```

```{r}
emajor_nodes0
```
## xml 政府開放
```{r}
read_xml("http://opendataap2.e-land.gov.tw/resource/files/2019-11-21/beff7621e386abc10f7e339114848aca.xml") ->xmlnodes0
```

