---
title: 競賽緣起
---
```{css, echo=F}
h1.title {
    font-size: 35px;
    /* align-content: center; */
    text-align: center;
}
```

___

<div class="divborder">

<p class="paragraph">
<br>
以軟體、手機應用程式、虛擬實境和雲端服務等技術整合，開發具潛在目標市場包含醫療、環境、教育、娛樂和智慧生活等的資訊科技創新活動。國立臺北大學經濟系辦理「第二屆國立臺北大學資料科學應用創新競賽」活動，期待參賽者能以「技術交流、團隊合作」的精神，在競賽中與實務接軌，發揮無窮的想像力，為新科技帶來不一樣的驚奇！
</p>

</div>

___

<br>
  <div class="title" >競賽方式</div>

___

<div id="timelineL">
<p>
<font size="6">初賽</font>
<br>
初賽須繳交作品計畫書，影片（選擇性）。
</p>
<p>
<font size="6">決賽名單公告</font>
<br>
評審依據繳交之文件選出12組決選名單。
</p>

<p>
<font size="6">人氣投票</font>
<br>
投票將納入決賽分數之10%
</p>
<p>
<font size="6">決賽/頒獎</font>
<br>
決賽參賽者需展示實體成果，並接受提問。
<br>
</p>
</div>



<div id="timelineR" class="vtl">
<div class="ewrap">
<div class="event">
<strong class="text">初賽</strong>
</div>
</div>
<div class="ewrap">
<div class="event">
<strong class="text">決選名單公告</strong>
</div>
</div>
<div class="ewrap">
<div class="event">
<strong class="text">人氣投票</strong>
</div>
</div>
<div class="ewrap">
<div class="event">
<strong class="text">決賽/頒獎</strong>
</div>
</div>
</div>

<div style="clear:both;"></div>

___
<div class="title"> 決賽時間/地點 </div>
___

<div class="divborder2">
<font class="highlight"> 決賽時間 </font>
<p class="paragraph">
  109年4月11日
</p>

<font class="highlight"> 決賽地點 </font>
<p class="paragraph">
  國立臺北大學創業創新中心<br>(圖書館後方B1) 
</p>

</div>

___

<div class="title"> 決賽規則 </div>

___

<div class="divborder2">
<font class="highlight"> 報告時間 </font>
<p class="paragraph">
各組報告時間為8至15分鐘，工作人員於報告時間至7分鐘時舉牌提醒參賽隊伍。
報告完需接受評審提問。
</p>

<font class="highlight"> 報告內容 </font>
<p class="paragraph">
報告內容須包含實體作品展現。
</p>
</div>

___

<div class="title"> 競賽獎勵 </div>

___

<div class="divborder2">
<font class="highlight"> 第一名(1名) </font>
<p class="paragraph">
獎金新台幣3萬元。
</p>

<font class="highlight"> 第二名(1名) </font>
<p class="paragraph">
獎金新台幣2萬元。
</p>
<font class="highlight"> 第三名(1名) </font>
<p class="paragraph">
獎金新台幣1萬元。
</p>

<font class="highlight"> 佳作(最多3名) </font>
<p class="paragraph">
獎金新台幣5,000元。
</p>
獎項評定及頒發由評選委員會議決議之，必要時得以從缺辦理。
</div>

<br>

___

<div class="title"> 注意事項 </div>

<li>
參賽作品之著作權，歸屬參賽團隊或成員個人，但主辦單位擁有非商業行為目的的重製、下載及公開展示等權利。
</li>
<li>
凡報名參加本競賽者，視為已閱讀並完全同意遵守本活動之一切規定，若有未盡事宜或不可抗拒因素而有所異動，主辦單位保有變更內容之權力。
</li>
<li>
參賽者所繳交影片並無侵權行為。創作過程或產出如有參考或引用他人作品者，參賽者已註明其來源出處及原作者姓名，或取得著作財產權人之授權。如有任何糾紛，均由個人承擔，非屬國立臺北大學經濟系單位之責。涉及他人智慧財產權者，參賽者應依相關法令規定辦理。違反規定者，該作品取消參賽資格。
</li>
<br>